In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from datetime import date
from sklearn.preprocessing import MinMaxScaler
import seaborn as sa

In [2]:
path ="D:\Artifical Intelligence\Dataset\superstore_data.csv"
data=pd.read_csv(path)
data.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0      1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1      2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2      3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3      4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4      5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

      CustomerName    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases   
1     42420.0   South  FUR-CH-10000454        Furniture       Chairs   
2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels   
3     33311.0   South  FUR-TA-10000577        Furniture       Tables   
4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600       2.0   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0   
4                     Eldon Fold 'N Roll Cart System   22.3680       2.0   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [3]:
data.drop(["Row ID"] ,axis =1,inplace =True )

In [4]:
data.isnull().sum()

Order ID          0
Order Date      302
Ship Date       302
Ship Mode       302
Customer ID     302
CustomerName    302
Segment         302
Country         302
City            302
State           302
Postal Code     302
Region          302
Product ID      302
Category        302
Sub-Category    302
Product Name    302
Sales           302
Quantity        302
Discount        302
Profit          302
dtype: int64

In [5]:
data = data.drop(data.index[-303:-1])

In [6]:
data = data.drop(data.index[-1])

In [7]:
data.duplicated().sum()

1

In [8]:
data.drop_duplicates(keep='first').shape

(9992, 20)

In [9]:
ds=data[["Category","Discount","Sales","Profit"]]

In [10]:
ds.head()

Category  Discount     Sales    Profit
0        Furniture      0.00  261.9600   41.9136
1        Furniture      0.00  731.9400  219.5820
2  Office Supplies      0.00   14.6200    6.8714
3        Furniture      0.45  957.5775 -383.0310
4  Office Supplies      0.20   22.3680    2.5164

In [11]:
df=pd.get_dummies(ds)

In [12]:
x=df.drop("Profit",axis=1)

In [13]:
x.head()

Discount     Sales  Category_Furniture  Category_Office Supplies  \
0      0.00  261.9600                   1                         0   
1      0.00  731.9400                   1                         0   
2      0.00   14.6200                   0                         1   
3      0.45  957.5775                   1                         0   
4      0.20   22.3680                   0                         1   

   Category_Technology  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [14]:
y=ds[["Profit"]]

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=0)

In [16]:
r =RandomForestRegressor(bootstrap=True,n_estimators = 100, oob_score = False, n_jobs = -1,random_state =0,max_depth=None,max_features = "auto", min_samples_leaf = 1, min_samples_split=2)

In [17]:
r.fit(x_train,y_train)

C:\Users\Aizaz\AppData\Local\Temp/ipykernel_1828/2342471624.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  r.fit(x_train,y_train)


RandomForestRegressor(n_jobs=-1, random_state=0)

In [18]:
r.score(x_train,y_train),r.score(x_test,y_test)

(0.9354254173928852, 0.828446759852367)

### param_grid

In [19]:
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 80, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [2,4]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]
random_state=[0,5]

In [20]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
                'random_state':random_state }
print(param_grid)

{'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72, 80], 'max_features': ['auto', 'sqrt'], 'max_depth': [2, 4], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False], 'random_state': [0, 5]}


In [21]:
rf = RandomForestRegressor()

In [22]:
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = rf, param_grid = param_grid, cv=5,n_jobs=-1)

In [23]:
rf_Grid.fit(x_train, y_train)

D:\Install\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:880: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [2, 4],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72,
                                          80],
                         'random_state': [0, 5]})

In [24]:
rf_Grid.best_params_

{'bootstrap': True,
 'max_depth': 4,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 17,
 'random_state': 5}

In [25]:
print (f'Train Accuracy - : {rf_Grid.score(x_train,y_train):.3f}')
print (f'Test Accuracy - : {rf_Grid.score(x_test,y_test):.3f}')

Train Accuracy - : 0.720
Test Accuracy - : 0.567


### OneHotEncoder

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
enc = OneHotEncoder()

In [28]:
X_onehot = enc.fit_transform(x).toarray()

In [40]:
x_train, x_test, y_train, y_test = train_test_split(X_onehot, y,random_state=0)

In [42]:
#r.fit(x_train,y_train)

In [ ]:
r.score(x_train,y_train),r.score(x_test,y_test)

### Cross-validation

In [34]:
from sklearn.model_selection import cross_val_score

In [38]:
Cross_validation = cross_val_score(r,x,y)

D:\Install\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Install\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Install\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Install\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d a

In [39]:
Cross_validation

array([ 0.43326882, -0.23611332,  0.81338723,  0.73596716,  0.88602376])

In [137]:
asd =RandomForestRegressor(bootstrap=True,n_estimators = 100, oob_score = False, n_jobs = -1,random_state =0,max_depth=40,max_features = "auto", min_samples_leaf = 1, min_samples_split=2)

In [138]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=3)

In [139]:
asd.fit(x_train,y_train)

C:\Users\Aizaz\AppData\Local\Temp/ipykernel_1828/2011054744.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  asd.fit(x_train,y_train)


RandomForestRegressor(max_depth=40, n_jobs=-1, random_state=0)

In [140]:
asd.score(x_train,y_train),asd.score(x_test,y_test)

(0.9376943128771964, 0.8689123332418465)

In [141]:
df.head()

Discount     Sales    Profit  Category_Furniture  Category_Office Supplies  \
0      0.00  261.9600   41.9136                   1                         0   
1      0.00  731.9400  219.5820                   1                         0   
2      0.00   14.6200    6.8714                   0                         1   
3      0.45  957.5775 -383.0310                   1                         0   
4      0.20   22.3680    2.5164                   0                         1   

   Category_Technology  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [142]:
guess=[[0.2,22.368,0,1,0]]

In [143]:
pre =asd.predict(guess)
pre

array([2.45037351])

In [149]:
g1=[[0,14.62,0,1,0]]

In [150]:
pre =asd.predict(g1)
pre

array([6.85664791])

In [151]:
df[20:22]

Discount  Sales  Profit  Category_Furniture  Category_Office Supplies  \
20       0.2  22.72  7.3840                   0                         1   
21       0.0  19.46  5.0596                   0                         1   

    Category_Technology  
20                    0  
21                    0

In [152]:
g2=[[0,19.46,0,1,0]]

In [153]:
pre =asd.predict(g2)
pre

array([5.48762361])

In [155]:
df[50:51]

Discount  Sales   Profit  Category_Furniture  Category_Office Supplies  \
50       0.0  75.18  35.3346                   0                         1   

    Category_Technology  
50                    0

In [156]:
g3=[[0,75.18,0,1,0]]

In [157]:
pre =asd.predict(g3)
pre

array([35.300114])

In [158]:
df[80:81]

Discount  Sales  Profit  Category_Furniture  Category_Office Supplies  \
80       0.0  16.74  8.0352                   0                         1   

    Category_Technology  
80                    0

In [159]:
g4=[[0,16.74,0,1,0]]
pre =asd.predict(g4)
pre

array([6.98485537])

In [168]:
df[124:125]

Discount    Sales  Profit  Category_Furniture  Category_Office Supplies  \
124       0.3  600.558 -8.5794                   1                         0   

     Category_Technology  
124                    0

In [169]:
g5=[[0.3,600,1,0,0]]
pre =asd.predict(g5)
pre

array([-13.220749])

In [176]:
df[239:240]

Discount   Sales  Profit  Category_Furniture  Category_Office Supplies  \
239       0.6  11.688 -4.6752                   1                         0   

     Category_Technology  
239                    0

In [175]:
g6=[[0.6,11.688,1,0,0]]
pre =asd.predict(g6)
pre

array([-5.63209])

In [179]:
df[552:553]

Discount   Sales  Profit  Category_Furniture  Category_Office Supplies  \
552       0.2  34.504  6.0382                   1                         0   

     Category_Technology  
552                    0

In [180]:
g7=[[0.2,34.5,1,0,0]]
pre =asd.predict(g7)
pre

array([6.095388])

In [189]:
df[1009:1010]

Discount   Sales  Profit  Category_Furniture  Category_Office Supplies  \
1009       0.2  95.984   5.999                   0                         0   

      Category_Technology  
1009                    1

In [188]:
g8=[[0.2,95.984,0,0,1]]
pre =asd.predict(g8)
pre

array([7.5984309])

In [190]:
df[5009:5010]

Discount    Sales   Profit  Category_Furniture  \
5009       0.4  791.964 -131.994                   0   

      Category_Office Supplies  Category_Technology  
5009                         0                    1

In [191]:
g9=[[0.4,791.964,0,0,1]]
pre =asd.predict(g9)
pre

array([-143.35809])

In [192]:
df[7009:7010]

Discount   Sales  Profit  Category_Furniture  Category_Office Supplies  \
7009       0.2  25.984 -3.8976                   1                         0   

      Category_Technology  
7009                    0

In [193]:
g10=[[0.2,25.984,1,0,0]]
pre =asd.predict(g10)
pre

array([-2.7427904])